# theme = "nord"
theme = "rose_pine"
# or other variant
# theme = "rose_pine_moon"
# theme = "rose_pine_dawn"

[editor]
line-number = "relative"
mouse = true

cursorline = true
cursorcolumn = false

bufferline = "always"
# never, always, multiple

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
# bar, block, underline

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

